import type { SimulationIntakePack } from "./types";

export const creativeTestingPack: SimulationIntakePack = {
  simulationType: "creative_testing",
  version: "creative_testing.intake.v1",
  label: "크리에이티브 비교",
  routeHints: [
    "헤드라인",
    "카피",
    "광고 문구",
    "상세페이지",
    "랜딩",
    "메시지",
    "문구",
    "소재",
  ],
  minConfidenceToAutoSelect: 0.72,
  formFieldOrder: ["product_description", "target_customers", "main_benefit", "tone"],
  slots: [
    {
      id: "creative_surface",
      label: "테스트할 문구 위치",
      family: "context",
      importance: "critical",
      dataType: "text",
      canInfer: true,
      canGenerate: false,
      needsReviewWhenGenerated: false,
      placeholder: "예: 상세페이지 헤드라인",
    },
    {
      id: "product_description",
      label: "제품 설명",
      family: "object",
      importance: "critical",
      dataType: "textarea",
      canInfer: true,
      canGenerate: false,
      needsReviewWhenGenerated: false,
      placeholder: "예: 블로그를 작성하는 윈도우 프로그램",
      helperText: "무엇을 팔거나 알리고 싶은지 한두 문장으로 적어주세요.",
    },
    {
      id: "creative_candidates",
      label: "비교할 후보 문구",
      family: "options",
      importance: "critical",
      dataType: "multi_text",
      minItems: 2,
      maxItems: 10,
      recommendedItems: 4,
      canInfer: false,
      canGenerate: true,
      needsReviewWhenGenerated: true,
      placeholder: "한 줄에 하나씩 입력하거나 비워두면 후보를 생성합니다.",
    },
    {
      id: "target_customers",
      label: "핵심 고객",
      family: "audience",
      importance: "recommended",
      dataType: "multi_text",
      minItems: 1,
      recommendedItems: 3,
      canInfer: true,
      canGenerate: true,
      needsReviewWhenGenerated: true,
      placeholder: "예: 네이버 블로그로 마케팅하는 소상공인",
      helperText: "1개만 적어도 괜찮습니다. 나머지는 추정할 수 있습니다.",
    },
    {
      id: "main_benefit",
      label: "가장 큰 장점",
      family: "criteria",
      importance: "recommended",
      dataType: "textarea",
      canInfer: true,
      canGenerate: true,
      needsReviewWhenGenerated: true,
      placeholder: "예: 글 작성 시간을 줄이고 검색 유입용 글을 쉽게 만듭니다.",
    },
    {
      id: "tone",
      label: "원하는 톤",
      family: "constraints",
      importance: "optional",
      dataType: "single_select",
      canInfer: true,
      canGenerate: false,
      needsReviewWhenGenerated: false,
      options: ["전환 중심", "전문적", "친근함", "프리미엄", "SEO 중심"],
    },
    {
      id: "sample_size",
      label: "표본 수",
      family: "run_config",
      importance: "optional",
      dataType: "number",
      canInfer: false,
      canGenerate: false,
      needsReviewWhenGenerated: false,
    },
    {
      id: "seed",
      label: "시드",
      family: "run_config",
      importance: "optional",
      dataType: "number",
      canInfer: false,
      canGenerate: false,
      needsReviewWhenGenerated: false,
    },
  ],
};
